version: '3.1'

services:
  mariadb:
    image: mariadb:10.3
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: demo
      MYSQL_USER: changeme
      MYSQL_PASSWORD: changeme
  ms-jpa-rest:
    image: b0rr3g0/uca-workshop
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - mariadb
    environment:
      SPRING_PROFILES_ACTIVE: compose