apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.bbdd.secret.name }}"
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  mariadb-root-username: "{{ .Values.bbdd.secret.root_username }}"
  mariadb-root-password: "{{ .Values.bbdd.secret.root_password }}"
  mariadb-replication-password: "{{ .Values.bbdd.secret.replication_password }}"
  mariadb-password: "{{ .Values.bbdd.secret.password }}"